# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: koinos/chain/object_spaces.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='koinos/chain/object_spaces.proto',
  package='koinos.chain',
  syntax='proto3',
  serialized_options=b'Z5github.com/koinos/koinos-proto-golang/v2/koinos/chain',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n koinos/chain/object_spaces.proto\x12\x0ckoinos.chain*~\n\x0fsystem_space_id\x12\x0c\n\x08metadata\x10\x00\x12\x18\n\x14system_call_dispatch\x10\x01\x12\x15\n\x11\x63ontract_bytecode\x10\x02\x12\x15\n\x11\x63ontract_metadata\x10\x03\x12\x15\n\x11transaction_nonce\x10\x04\x42\x37Z5github.com/koinos/koinos-proto-golang/v2/koinos/chainb\x06proto3'
)

_SYSTEM_SPACE_ID = _descriptor.EnumDescriptor(
  name='system_space_id',
  full_name='koinos.chain.system_space_id',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='metadata', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='system_call_dispatch', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='contract_bytecode', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='contract_metadata', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='transaction_nonce', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=50,
  serialized_end=176,
)
_sym_db.RegisterEnumDescriptor(_SYSTEM_SPACE_ID)

system_space_id = enum_type_wrapper.EnumTypeWrapper(_SYSTEM_SPACE_ID)
metadata = 0
system_call_dispatch = 1
contract_bytecode = 2
contract_metadata = 3
transaction_nonce = 4


DESCRIPTOR.enum_types_by_name['system_space_id'] = _SYSTEM_SPACE_ID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
