# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: koinos/rpc/mempool/mempool_rpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from koinos.protocol import protocol_pb2 as koinos_dot_protocol_dot_protocol__pb2
from koinos.rpc import rpc_pb2 as koinos_dot_rpc_dot_rpc__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='koinos/rpc/mempool/mempool_rpc.proto',
  package='koinos.rpc.mempool',
  syntax='proto3',
  serialized_options=b'Z8github.com/koinos/koinos-proto-golang/koinos/rpc/mempool',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$koinos/rpc/mempool/mempool_rpc.proto\x12\x12koinos.rpc.mempool\x1a\x1ekoinos/protocol/protocol.proto\x1a\x14koinos/rpc/rpc.proto\"h\n\'check_pending_account_resources_request\x12\r\n\x05payer\x18\x01 \x01(\x0c\x12\x18\n\x0cmax_payer_rc\x18\x02 \x01(\x04\x42\x02\x30\x01\x12\x14\n\x08rc_limit\x18\x03 \x01(\x04\x42\x02\x30\x01\";\n(check_pending_account_resources_response\x12\x0f\n\x07success\x18\x01 \x01(\x08\"5\n get_pending_transactions_request\x12\x11\n\x05limit\x18\x01 \x01(\x04\x42\x02\x30\x01\"W\n!get_pending_transactions_response\x12\x32\n\x0ctransactions\x18\x01 \x03(\x0b\x32\x1c.koinos.protocol.transaction\"\x8c\x02\n\x0fmempool_request\x12,\n\x08reserved\x18\x01 \x01(\x0b\x32\x18.koinos.rpc.reserved_rpcH\x00\x12\x66\n\x1f\x63heck_pending_account_resources\x18\x02 \x01(\x0b\x32;.koinos.rpc.mempool.check_pending_account_resources_requestH\x00\x12X\n\x18get_pending_transactions\x18\x03 \x01(\x0b\x32\x34.koinos.rpc.mempool.get_pending_transactions_requestH\x00\x42\t\n\x07request\"\xbd\x02\n\x10mempool_response\x12,\n\x08reserved\x18\x01 \x01(\x0b\x32\x18.koinos.rpc.reserved_rpcH\x00\x12+\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x1a.koinos.rpc.error_responseH\x00\x12g\n\x1f\x63heck_pending_account_resources\x18\x03 \x01(\x0b\x32<.koinos.rpc.mempool.check_pending_account_resources_responseH\x00\x12Y\n\x18get_pending_transactions\x18\x04 \x01(\x0b\x32\x35.koinos.rpc.mempool.get_pending_transactions_responseH\x00\x42\n\n\x08responseB:Z8github.com/koinos/koinos-proto-golang/koinos/rpc/mempoolb\x06proto3'
  ,
  dependencies=[koinos_dot_protocol_dot_protocol__pb2.DESCRIPTOR,koinos_dot_rpc_dot_rpc__pb2.DESCRIPTOR,])




_CHECK_PENDING_ACCOUNT_RESOURCES_REQUEST = _descriptor.Descriptor(
  name='check_pending_account_resources_request',
  full_name='koinos.rpc.mempool.check_pending_account_resources_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='payer', full_name='koinos.rpc.mempool.check_pending_account_resources_request.payer', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_payer_rc', full_name='koinos.rpc.mempool.check_pending_account_resources_request.max_payer_rc', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'0\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rc_limit', full_name='koinos.rpc.mempool.check_pending_account_resources_request.rc_limit', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'0\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=218,
)


_CHECK_PENDING_ACCOUNT_RESOURCES_RESPONSE = _descriptor.Descriptor(
  name='check_pending_account_resources_response',
  full_name='koinos.rpc.mempool.check_pending_account_resources_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='koinos.rpc.mempool.check_pending_account_resources_response.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=279,
)


_GET_PENDING_TRANSACTIONS_REQUEST = _descriptor.Descriptor(
  name='get_pending_transactions_request',
  full_name='koinos.rpc.mempool.get_pending_transactions_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='limit', full_name='koinos.rpc.mempool.get_pending_transactions_request.limit', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'0\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=334,
)


_GET_PENDING_TRANSACTIONS_RESPONSE = _descriptor.Descriptor(
  name='get_pending_transactions_response',
  full_name='koinos.rpc.mempool.get_pending_transactions_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='transactions', full_name='koinos.rpc.mempool.get_pending_transactions_response.transactions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=336,
  serialized_end=423,
)


_MEMPOOL_REQUEST = _descriptor.Descriptor(
  name='mempool_request',
  full_name='koinos.rpc.mempool.mempool_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reserved', full_name='koinos.rpc.mempool.mempool_request.reserved', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='check_pending_account_resources', full_name='koinos.rpc.mempool.mempool_request.check_pending_account_resources', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='get_pending_transactions', full_name='koinos.rpc.mempool.mempool_request.get_pending_transactions', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='request', full_name='koinos.rpc.mempool.mempool_request.request',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=426,
  serialized_end=694,
)


_MEMPOOL_RESPONSE = _descriptor.Descriptor(
  name='mempool_response',
  full_name='koinos.rpc.mempool.mempool_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reserved', full_name='koinos.rpc.mempool.mempool_response.reserved', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='koinos.rpc.mempool.mempool_response.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='check_pending_account_resources', full_name='koinos.rpc.mempool.mempool_response.check_pending_account_resources', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='get_pending_transactions', full_name='koinos.rpc.mempool.mempool_response.get_pending_transactions', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='response', full_name='koinos.rpc.mempool.mempool_response.response',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=697,
  serialized_end=1014,
)

_GET_PENDING_TRANSACTIONS_RESPONSE.fields_by_name['transactions'].message_type = koinos_dot_protocol_dot_protocol__pb2._TRANSACTION
_MEMPOOL_REQUEST.fields_by_name['reserved'].message_type = koinos_dot_rpc_dot_rpc__pb2._RESERVED_RPC
_MEMPOOL_REQUEST.fields_by_name['check_pending_account_resources'].message_type = _CHECK_PENDING_ACCOUNT_RESOURCES_REQUEST
_MEMPOOL_REQUEST.fields_by_name['get_pending_transactions'].message_type = _GET_PENDING_TRANSACTIONS_REQUEST
_MEMPOOL_REQUEST.oneofs_by_name['request'].fields.append(
  _MEMPOOL_REQUEST.fields_by_name['reserved'])
_MEMPOOL_REQUEST.fields_by_name['reserved'].containing_oneof = _MEMPOOL_REQUEST.oneofs_by_name['request']
_MEMPOOL_REQUEST.oneofs_by_name['request'].fields.append(
  _MEMPOOL_REQUEST.fields_by_name['check_pending_account_resources'])
_MEMPOOL_REQUEST.fields_by_name['check_pending_account_resources'].containing_oneof = _MEMPOOL_REQUEST.oneofs_by_name['request']
_MEMPOOL_REQUEST.oneofs_by_name['request'].fields.append(
  _MEMPOOL_REQUEST.fields_by_name['get_pending_transactions'])
_MEMPOOL_REQUEST.fields_by_name['get_pending_transactions'].containing_oneof = _MEMPOOL_REQUEST.oneofs_by_name['request']
_MEMPOOL_RESPONSE.fields_by_name['reserved'].message_type = koinos_dot_rpc_dot_rpc__pb2._RESERVED_RPC
_MEMPOOL_RESPONSE.fields_by_name['error'].message_type = koinos_dot_rpc_dot_rpc__pb2._ERROR_RESPONSE
_MEMPOOL_RESPONSE.fields_by_name['check_pending_account_resources'].message_type = _CHECK_PENDING_ACCOUNT_RESOURCES_RESPONSE
_MEMPOOL_RESPONSE.fields_by_name['get_pending_transactions'].message_type = _GET_PENDING_TRANSACTIONS_RESPONSE
_MEMPOOL_RESPONSE.oneofs_by_name['response'].fields.append(
  _MEMPOOL_RESPONSE.fields_by_name['reserved'])
_MEMPOOL_RESPONSE.fields_by_name['reserved'].containing_oneof = _MEMPOOL_RESPONSE.oneofs_by_name['response']
_MEMPOOL_RESPONSE.oneofs_by_name['response'].fields.append(
  _MEMPOOL_RESPONSE.fields_by_name['error'])
_MEMPOOL_RESPONSE.fields_by_name['error'].containing_oneof = _MEMPOOL_RESPONSE.oneofs_by_name['response']
_MEMPOOL_RESPONSE.oneofs_by_name['response'].fields.append(
  _MEMPOOL_RESPONSE.fields_by_name['check_pending_account_resources'])
_MEMPOOL_RESPONSE.fields_by_name['check_pending_account_resources'].containing_oneof = _MEMPOOL_RESPONSE.oneofs_by_name['response']
_MEMPOOL_RESPONSE.oneofs_by_name['response'].fields.append(
  _MEMPOOL_RESPONSE.fields_by_name['get_pending_transactions'])
_MEMPOOL_RESPONSE.fields_by_name['get_pending_transactions'].containing_oneof = _MEMPOOL_RESPONSE.oneofs_by_name['response']
DESCRIPTOR.message_types_by_name['check_pending_account_resources_request'] = _CHECK_PENDING_ACCOUNT_RESOURCES_REQUEST
DESCRIPTOR.message_types_by_name['check_pending_account_resources_response'] = _CHECK_PENDING_ACCOUNT_RESOURCES_RESPONSE
DESCRIPTOR.message_types_by_name['get_pending_transactions_request'] = _GET_PENDING_TRANSACTIONS_REQUEST
DESCRIPTOR.message_types_by_name['get_pending_transactions_response'] = _GET_PENDING_TRANSACTIONS_RESPONSE
DESCRIPTOR.message_types_by_name['mempool_request'] = _MEMPOOL_REQUEST
DESCRIPTOR.message_types_by_name['mempool_response'] = _MEMPOOL_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

check_pending_account_resources_request = _reflection.GeneratedProtocolMessageType('check_pending_account_resources_request', (_message.Message,), {
  'DESCRIPTOR' : _CHECK_PENDING_ACCOUNT_RESOURCES_REQUEST,
  '__module__' : 'koinos.rpc.mempool.mempool_rpc_pb2'
  # @@protoc_insertion_point(class_scope:koinos.rpc.mempool.check_pending_account_resources_request)
  })
_sym_db.RegisterMessage(check_pending_account_resources_request)

check_pending_account_resources_response = _reflection.GeneratedProtocolMessageType('check_pending_account_resources_response', (_message.Message,), {
  'DESCRIPTOR' : _CHECK_PENDING_ACCOUNT_RESOURCES_RESPONSE,
  '__module__' : 'koinos.rpc.mempool.mempool_rpc_pb2'
  # @@protoc_insertion_point(class_scope:koinos.rpc.mempool.check_pending_account_resources_response)
  })
_sym_db.RegisterMessage(check_pending_account_resources_response)

get_pending_transactions_request = _reflection.GeneratedProtocolMessageType('get_pending_transactions_request', (_message.Message,), {
  'DESCRIPTOR' : _GET_PENDING_TRANSACTIONS_REQUEST,
  '__module__' : 'koinos.rpc.mempool.mempool_rpc_pb2'
  # @@protoc_insertion_point(class_scope:koinos.rpc.mempool.get_pending_transactions_request)
  })
_sym_db.RegisterMessage(get_pending_transactions_request)

get_pending_transactions_response = _reflection.GeneratedProtocolMessageType('get_pending_transactions_response', (_message.Message,), {
  'DESCRIPTOR' : _GET_PENDING_TRANSACTIONS_RESPONSE,
  '__module__' : 'koinos.rpc.mempool.mempool_rpc_pb2'
  # @@protoc_insertion_point(class_scope:koinos.rpc.mempool.get_pending_transactions_response)
  })
_sym_db.RegisterMessage(get_pending_transactions_response)

mempool_request = _reflection.GeneratedProtocolMessageType('mempool_request', (_message.Message,), {
  'DESCRIPTOR' : _MEMPOOL_REQUEST,
  '__module__' : 'koinos.rpc.mempool.mempool_rpc_pb2'
  # @@protoc_insertion_point(class_scope:koinos.rpc.mempool.mempool_request)
  })
_sym_db.RegisterMessage(mempool_request)

mempool_response = _reflection.GeneratedProtocolMessageType('mempool_response', (_message.Message,), {
  'DESCRIPTOR' : _MEMPOOL_RESPONSE,
  '__module__' : 'koinos.rpc.mempool.mempool_rpc_pb2'
  # @@protoc_insertion_point(class_scope:koinos.rpc.mempool.mempool_response)
  })
_sym_db.RegisterMessage(mempool_response)


DESCRIPTOR._options = None
_CHECK_PENDING_ACCOUNT_RESOURCES_REQUEST.fields_by_name['max_payer_rc']._options = None
_CHECK_PENDING_ACCOUNT_RESOURCES_REQUEST.fields_by_name['rc_limit']._options = None
_GET_PENDING_TRANSACTIONS_REQUEST.fields_by_name['limit']._options = None
# @@protoc_insertion_point(module_scope)
