# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: koinos/contracts/pow/pow.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='koinos/contracts/pow/pow.proto',
  package='koinos.contracts.pow',
  syntax='proto3',
  serialized_options=b'Z:github.com/koinos/koinos-proto-golang/koinos/contracts/pow',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1ekoinos/contracts/pow/pow.proto\x12\x14koinos.contracts.pow\"y\n\x13\x64ifficulty_metadata\x12\x0e\n\x06target\x18\x01 \x01(\x0c\x12\x1b\n\x0flast_block_time\x18\x02 \x01(\x04\x42\x02\x30\x01\x12\x12\n\ndifficulty\x18\x03 \x01(\x0c\x12!\n\x15target_block_interval\x18\x04 \x01(\x04\x42\x02\x30\x01\"#\n!get_difficulty_metadata_arguments\"Z\n\x1eget_difficulty_metadata_result\x12\x38\n\x05value\x18\x01 \x01(\x0b\x32).koinos.contracts.pow.difficulty_metadata\"B\n\x12pow_signature_data\x12\r\n\x05nonce\x18\x01 \x01(\x0c\x12\x1d\n\x15recoverable_signature\x18\x02 \x01(\x0c\x42<Z:github.com/koinos/koinos-proto-golang/koinos/contracts/powb\x06proto3'
)




_DIFFICULTY_METADATA = _descriptor.Descriptor(
  name='difficulty_metadata',
  full_name='koinos.contracts.pow.difficulty_metadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='target', full_name='koinos.contracts.pow.difficulty_metadata.target', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_block_time', full_name='koinos.contracts.pow.difficulty_metadata.last_block_time', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'0\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='difficulty', full_name='koinos.contracts.pow.difficulty_metadata.difficulty', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target_block_interval', full_name='koinos.contracts.pow.difficulty_metadata.target_block_interval', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'0\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=177,
)


_GET_DIFFICULTY_METADATA_ARGUMENTS = _descriptor.Descriptor(
  name='get_difficulty_metadata_arguments',
  full_name='koinos.contracts.pow.get_difficulty_metadata_arguments',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=214,
)


_GET_DIFFICULTY_METADATA_RESULT = _descriptor.Descriptor(
  name='get_difficulty_metadata_result',
  full_name='koinos.contracts.pow.get_difficulty_metadata_result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='koinos.contracts.pow.get_difficulty_metadata_result.value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=306,
)


_POW_SIGNATURE_DATA = _descriptor.Descriptor(
  name='pow_signature_data',
  full_name='koinos.contracts.pow.pow_signature_data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nonce', full_name='koinos.contracts.pow.pow_signature_data.nonce', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='recoverable_signature', full_name='koinos.contracts.pow.pow_signature_data.recoverable_signature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=374,
)

_GET_DIFFICULTY_METADATA_RESULT.fields_by_name['value'].message_type = _DIFFICULTY_METADATA
DESCRIPTOR.message_types_by_name['difficulty_metadata'] = _DIFFICULTY_METADATA
DESCRIPTOR.message_types_by_name['get_difficulty_metadata_arguments'] = _GET_DIFFICULTY_METADATA_ARGUMENTS
DESCRIPTOR.message_types_by_name['get_difficulty_metadata_result'] = _GET_DIFFICULTY_METADATA_RESULT
DESCRIPTOR.message_types_by_name['pow_signature_data'] = _POW_SIGNATURE_DATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

difficulty_metadata = _reflection.GeneratedProtocolMessageType('difficulty_metadata', (_message.Message,), {
  'DESCRIPTOR' : _DIFFICULTY_METADATA,
  '__module__' : 'koinos.contracts.pow.pow_pb2'
  # @@protoc_insertion_point(class_scope:koinos.contracts.pow.difficulty_metadata)
  })
_sym_db.RegisterMessage(difficulty_metadata)

get_difficulty_metadata_arguments = _reflection.GeneratedProtocolMessageType('get_difficulty_metadata_arguments', (_message.Message,), {
  'DESCRIPTOR' : _GET_DIFFICULTY_METADATA_ARGUMENTS,
  '__module__' : 'koinos.contracts.pow.pow_pb2'
  # @@protoc_insertion_point(class_scope:koinos.contracts.pow.get_difficulty_metadata_arguments)
  })
_sym_db.RegisterMessage(get_difficulty_metadata_arguments)

get_difficulty_metadata_result = _reflection.GeneratedProtocolMessageType('get_difficulty_metadata_result', (_message.Message,), {
  'DESCRIPTOR' : _GET_DIFFICULTY_METADATA_RESULT,
  '__module__' : 'koinos.contracts.pow.pow_pb2'
  # @@protoc_insertion_point(class_scope:koinos.contracts.pow.get_difficulty_metadata_result)
  })
_sym_db.RegisterMessage(get_difficulty_metadata_result)

pow_signature_data = _reflection.GeneratedProtocolMessageType('pow_signature_data', (_message.Message,), {
  'DESCRIPTOR' : _POW_SIGNATURE_DATA,
  '__module__' : 'koinos.contracts.pow.pow_pb2'
  # @@protoc_insertion_point(class_scope:koinos.contracts.pow.pow_signature_data)
  })
_sym_db.RegisterMessage(pow_signature_data)


DESCRIPTOR._options = None
_DIFFICULTY_METADATA.fields_by_name['last_block_time']._options = None
_DIFFICULTY_METADATA.fields_by_name['target_block_interval']._options = None
# @@protoc_insertion_point(module_scope)
