# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: koinos/options.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='koinos/options.proto',
  package='koinos',
  syntax='proto3',
  serialized_options=b'Z,github.com/koinos/koinos-proto-golang/koinos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14koinos/options.proto\x12\x06koinos\x1a google/protobuf/descriptor.proto*m\n\nbytes_type\x12\n\n\x06\x42\x41SE64\x10\x00\x12\n\n\x06\x42\x41SE58\x10\x01\x12\x07\n\x03HEX\x10\x02\x12\x0c\n\x08\x42LOCK_ID\x10\x03\x12\x12\n\x0eTRANSACTION_ID\x10\x04\x12\x0f\n\x0b\x43ONTRACT_ID\x10\x05\x12\x0b\n\x07\x41\x44\x44RESS\x10\x06:E\n\x05\x62type\x12\x1d.google.protobuf.FieldOptions\x18\xd0\x86\x03 \x01(\x0e\x32\x12.koinos.bytes_type\x88\x01\x01\x42.Z,github.com/koinos/koinos-proto-golang/koinosb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])

_BYTES_TYPE = _descriptor.EnumDescriptor(
  name='bytes_type',
  full_name='koinos.bytes_type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BASE64', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BASE58', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HEX', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BLOCK_ID', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TRANSACTION_ID', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CONTRACT_ID', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ADDRESS', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=66,
  serialized_end=175,
)
_sym_db.RegisterEnumDescriptor(_BYTES_TYPE)

bytes_type = enum_type_wrapper.EnumTypeWrapper(_BYTES_TYPE)
BASE64 = 0
BASE58 = 1
HEX = 2
BLOCK_ID = 3
TRANSACTION_ID = 4
CONTRACT_ID = 5
ADDRESS = 6

BTYPE_FIELD_NUMBER = 50000
btype = _descriptor.FieldDescriptor(
  name='btype', full_name='koinos.btype', index=0,
  number=50000, type=14, cpp_type=8, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)

DESCRIPTOR.enum_types_by_name['bytes_type'] = _BYTES_TYPE
DESCRIPTOR.extensions_by_name['btype'] = btype
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

btype.enum_type = _BYTES_TYPE
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(btype)

DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
