# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: koinos/contracts/resources/resources.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='koinos/contracts/resources/resources.proto',
  package='koinos.contracts.resources',
  syntax='proto3',
  serialized_options=b'Z@github.com/koinos/koinos-proto-golang/koinos/contracts/resources',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n*koinos/contracts/resources/resources.proto\x12\x1akoinos.contracts.resources\"p\n\x06market\x12\x1b\n\x0fresource_supply\x18\x01 \x01(\x04\x42\x02\x30\x01\x12\x16\n\nrc_reserve\x18\x02 \x01(\x04\x42\x02\x30\x01\x12\x18\n\x0c\x62lock_budget\x18\x03 \x01(\x04\x42\x02\x30\x01\x12\x17\n\x0b\x62lock_limit\x18\x04 \x01(\x04\x42\x02\x30\x01\"\xca\x01\n\x10resource_markets\x12\x38\n\x0c\x64isk_storage\x18\x01 \x01(\x0b\x32\".koinos.contracts.resources.market\x12=\n\x11network_bandwidth\x18\x02 \x01(\x0b\x32\".koinos.contracts.resources.market\x12=\n\x11\x63ompute_bandwidth\x18\x03 \x01(\x0b\x32\".koinos.contracts.resources.market\" \n\x1eget_resource_markets_arguments\"Z\n\x1bget_resource_markets_result\x12;\n\x05value\x18\x01 \x01(\x0b\x32,.koinos.contracts.resources.resource_marketsBBZ@github.com/koinos/koinos-proto-golang/koinos/contracts/resourcesb\x06proto3'
)




_MARKET = _descriptor.Descriptor(
  name='market',
  full_name='koinos.contracts.resources.market',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resource_supply', full_name='koinos.contracts.resources.market.resource_supply', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'0\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rc_reserve', full_name='koinos.contracts.resources.market.rc_reserve', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'0\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='block_budget', full_name='koinos.contracts.resources.market.block_budget', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'0\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='block_limit', full_name='koinos.contracts.resources.market.block_limit', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'0\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=186,
)


_RESOURCE_MARKETS = _descriptor.Descriptor(
  name='resource_markets',
  full_name='koinos.contracts.resources.resource_markets',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='disk_storage', full_name='koinos.contracts.resources.resource_markets.disk_storage', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='network_bandwidth', full_name='koinos.contracts.resources.resource_markets.network_bandwidth', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='compute_bandwidth', full_name='koinos.contracts.resources.resource_markets.compute_bandwidth', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=391,
)


_GET_RESOURCE_MARKETS_ARGUMENTS = _descriptor.Descriptor(
  name='get_resource_markets_arguments',
  full_name='koinos.contracts.resources.get_resource_markets_arguments',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=393,
  serialized_end=425,
)


_GET_RESOURCE_MARKETS_RESULT = _descriptor.Descriptor(
  name='get_resource_markets_result',
  full_name='koinos.contracts.resources.get_resource_markets_result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='koinos.contracts.resources.get_resource_markets_result.value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=427,
  serialized_end=517,
)

_RESOURCE_MARKETS.fields_by_name['disk_storage'].message_type = _MARKET
_RESOURCE_MARKETS.fields_by_name['network_bandwidth'].message_type = _MARKET
_RESOURCE_MARKETS.fields_by_name['compute_bandwidth'].message_type = _MARKET
_GET_RESOURCE_MARKETS_RESULT.fields_by_name['value'].message_type = _RESOURCE_MARKETS
DESCRIPTOR.message_types_by_name['market'] = _MARKET
DESCRIPTOR.message_types_by_name['resource_markets'] = _RESOURCE_MARKETS
DESCRIPTOR.message_types_by_name['get_resource_markets_arguments'] = _GET_RESOURCE_MARKETS_ARGUMENTS
DESCRIPTOR.message_types_by_name['get_resource_markets_result'] = _GET_RESOURCE_MARKETS_RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

market = _reflection.GeneratedProtocolMessageType('market', (_message.Message,), {
  'DESCRIPTOR' : _MARKET,
  '__module__' : 'koinos.contracts.resources.resources_pb2'
  # @@protoc_insertion_point(class_scope:koinos.contracts.resources.market)
  })
_sym_db.RegisterMessage(market)

resource_markets = _reflection.GeneratedProtocolMessageType('resource_markets', (_message.Message,), {
  'DESCRIPTOR' : _RESOURCE_MARKETS,
  '__module__' : 'koinos.contracts.resources.resources_pb2'
  # @@protoc_insertion_point(class_scope:koinos.contracts.resources.resource_markets)
  })
_sym_db.RegisterMessage(resource_markets)

get_resource_markets_arguments = _reflection.GeneratedProtocolMessageType('get_resource_markets_arguments', (_message.Message,), {
  'DESCRIPTOR' : _GET_RESOURCE_MARKETS_ARGUMENTS,
  '__module__' : 'koinos.contracts.resources.resources_pb2'
  # @@protoc_insertion_point(class_scope:koinos.contracts.resources.get_resource_markets_arguments)
  })
_sym_db.RegisterMessage(get_resource_markets_arguments)

get_resource_markets_result = _reflection.GeneratedProtocolMessageType('get_resource_markets_result', (_message.Message,), {
  'DESCRIPTOR' : _GET_RESOURCE_MARKETS_RESULT,
  '__module__' : 'koinos.contracts.resources.resources_pb2'
  # @@protoc_insertion_point(class_scope:koinos.contracts.resources.get_resource_markets_result)
  })
_sym_db.RegisterMessage(get_resource_markets_result)


DESCRIPTOR._options = None
_MARKET.fields_by_name['resource_supply']._options = None
_MARKET.fields_by_name['rc_reserve']._options = None
_MARKET.fields_by_name['block_budget']._options = None
_MARKET.fields_by_name['block_limit']._options = None
# @@protoc_insertion_point(module_scope)
