# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: koinos/contracts/claim/claim.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from koinos import options_pb2 as koinos_dot_options__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='koinos/contracts/claim/claim.proto',
  package='koinos.contracts.claim',
  syntax='proto3',
  serialized_options=b'Z<github.com/koinos/koinos-proto-golang/koinos/contracts/claim',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"koinos/contracts/claim/claim.proto\x12\x16koinos.contracts.claim\x1a\x14koinos/options.proto\"9\n\x0c\x63laim_status\x12\x18\n\x0ctoken_amount\x18\x01 \x01(\x04\x42\x02\x30\x01\x12\x0f\n\x07\x63laimed\x18\x02 \x01(\x08\",\n\x0f\x63laim_arguments\x12\x19\n\x0b\x65th_address\x18\x01 \x01(\x0c\x42\x04\x80\xb5\x18\x02\"\x0e\n\x0c\x63laim_resultB>Z<github.com/koinos/koinos-proto-golang/koinos/contracts/claimb\x06proto3'
  ,
  dependencies=[koinos_dot_options__pb2.DESCRIPTOR,])




_CLAIM_STATUS = _descriptor.Descriptor(
  name='claim_status',
  full_name='koinos.contracts.claim.claim_status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='token_amount', full_name='koinos.contracts.claim.claim_status.token_amount', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'0\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='claimed', full_name='koinos.contracts.claim.claim_status.claimed', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=141,
)


_CLAIM_ARGUMENTS = _descriptor.Descriptor(
  name='claim_arguments',
  full_name='koinos.contracts.claim.claim_arguments',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='eth_address', full_name='koinos.contracts.claim.claim_arguments.eth_address', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\200\265\030\002', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=187,
)


_CLAIM_RESULT = _descriptor.Descriptor(
  name='claim_result',
  full_name='koinos.contracts.claim.claim_result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=203,
)

DESCRIPTOR.message_types_by_name['claim_status'] = _CLAIM_STATUS
DESCRIPTOR.message_types_by_name['claim_arguments'] = _CLAIM_ARGUMENTS
DESCRIPTOR.message_types_by_name['claim_result'] = _CLAIM_RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

claim_status = _reflection.GeneratedProtocolMessageType('claim_status', (_message.Message,), {
  'DESCRIPTOR' : _CLAIM_STATUS,
  '__module__' : 'koinos.contracts.claim.claim_pb2'
  # @@protoc_insertion_point(class_scope:koinos.contracts.claim.claim_status)
  })
_sym_db.RegisterMessage(claim_status)

claim_arguments = _reflection.GeneratedProtocolMessageType('claim_arguments', (_message.Message,), {
  'DESCRIPTOR' : _CLAIM_ARGUMENTS,
  '__module__' : 'koinos.contracts.claim.claim_pb2'
  # @@protoc_insertion_point(class_scope:koinos.contracts.claim.claim_arguments)
  })
_sym_db.RegisterMessage(claim_arguments)

claim_result = _reflection.GeneratedProtocolMessageType('claim_result', (_message.Message,), {
  'DESCRIPTOR' : _CLAIM_RESULT,
  '__module__' : 'koinos.contracts.claim.claim_pb2'
  # @@protoc_insertion_point(class_scope:koinos.contracts.claim.claim_result)
  })
_sym_db.RegisterMessage(claim_result)


DESCRIPTOR._options = None
_CLAIM_STATUS.fields_by_name['token_amount']._options = None
_CLAIM_ARGUMENTS.fields_by_name['eth_address']._options = None
# @@protoc_insertion_point(module_scope)
