# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: koinos/rpc/p2p/p2p_rpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from koinos.rpc import rpc_pb2 as koinos_dot_rpc_dot_rpc__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='koinos/rpc/p2p/p2p_rpc.proto',
  package='koinos.rpc.p2p',
  syntax='proto3',
  serialized_options=b'Z7github.com/koinos/koinos-proto-golang/v2/koinos/rpc/p2p',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1ckoinos/rpc/p2p/p2p_rpc.proto\x12\x0ekoinos.rpc.p2p\x1a\x14koinos/rpc/rpc.proto\"\x1b\n\x19get_gossip_status_request\"-\n\x1aget_gossip_status_response\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x08\"\x8e\x01\n\x0bp2p_request\x12,\n\x08reserved\x18\x01 \x01(\x0b\x32\x18.koinos.rpc.reserved_rpcH\x00\x12\x46\n\x11get_gossip_status\x18\x02 \x01(\x0b\x32).koinos.rpc.p2p.get_gossip_status_requestH\x00\x42\t\n\x07request\"\xbc\x01\n\x0cp2p_response\x12,\n\x08reserved\x18\x01 \x01(\x0b\x32\x18.koinos.rpc.reserved_rpcH\x00\x12)\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x18.koinos.rpc.error_statusH\x00\x12G\n\x11get_gossip_status\x18\x03 \x01(\x0b\x32*.koinos.rpc.p2p.get_gossip_status_responseH\x00\x42\n\n\x08responseB9Z7github.com/koinos/koinos-proto-golang/v2/koinos/rpc/p2pb\x06proto3'
  ,
  dependencies=[koinos_dot_rpc_dot_rpc__pb2.DESCRIPTOR,])




_GET_GOSSIP_STATUS_REQUEST = _descriptor.Descriptor(
  name='get_gossip_status_request',
  full_name='koinos.rpc.p2p.get_gossip_status_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=97,
)


_GET_GOSSIP_STATUS_RESPONSE = _descriptor.Descriptor(
  name='get_gossip_status_response',
  full_name='koinos.rpc.p2p.get_gossip_status_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='enabled', full_name='koinos.rpc.p2p.get_gossip_status_response.enabled', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=144,
)


_P2P_REQUEST = _descriptor.Descriptor(
  name='p2p_request',
  full_name='koinos.rpc.p2p.p2p_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reserved', full_name='koinos.rpc.p2p.p2p_request.reserved', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='get_gossip_status', full_name='koinos.rpc.p2p.p2p_request.get_gossip_status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='request', full_name='koinos.rpc.p2p.p2p_request.request',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=147,
  serialized_end=289,
)


_P2P_RESPONSE = _descriptor.Descriptor(
  name='p2p_response',
  full_name='koinos.rpc.p2p.p2p_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reserved', full_name='koinos.rpc.p2p.p2p_response.reserved', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='koinos.rpc.p2p.p2p_response.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='get_gossip_status', full_name='koinos.rpc.p2p.p2p_response.get_gossip_status', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='response', full_name='koinos.rpc.p2p.p2p_response.response',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=292,
  serialized_end=480,
)

_P2P_REQUEST.fields_by_name['reserved'].message_type = koinos_dot_rpc_dot_rpc__pb2._RESERVED_RPC
_P2P_REQUEST.fields_by_name['get_gossip_status'].message_type = _GET_GOSSIP_STATUS_REQUEST
_P2P_REQUEST.oneofs_by_name['request'].fields.append(
  _P2P_REQUEST.fields_by_name['reserved'])
_P2P_REQUEST.fields_by_name['reserved'].containing_oneof = _P2P_REQUEST.oneofs_by_name['request']
_P2P_REQUEST.oneofs_by_name['request'].fields.append(
  _P2P_REQUEST.fields_by_name['get_gossip_status'])
_P2P_REQUEST.fields_by_name['get_gossip_status'].containing_oneof = _P2P_REQUEST.oneofs_by_name['request']
_P2P_RESPONSE.fields_by_name['reserved'].message_type = koinos_dot_rpc_dot_rpc__pb2._RESERVED_RPC
_P2P_RESPONSE.fields_by_name['error'].message_type = koinos_dot_rpc_dot_rpc__pb2._ERROR_STATUS
_P2P_RESPONSE.fields_by_name['get_gossip_status'].message_type = _GET_GOSSIP_STATUS_RESPONSE
_P2P_RESPONSE.oneofs_by_name['response'].fields.append(
  _P2P_RESPONSE.fields_by_name['reserved'])
_P2P_RESPONSE.fields_by_name['reserved'].containing_oneof = _P2P_RESPONSE.oneofs_by_name['response']
_P2P_RESPONSE.oneofs_by_name['response'].fields.append(
  _P2P_RESPONSE.fields_by_name['error'])
_P2P_RESPONSE.fields_by_name['error'].containing_oneof = _P2P_RESPONSE.oneofs_by_name['response']
_P2P_RESPONSE.oneofs_by_name['response'].fields.append(
  _P2P_RESPONSE.fields_by_name['get_gossip_status'])
_P2P_RESPONSE.fields_by_name['get_gossip_status'].containing_oneof = _P2P_RESPONSE.oneofs_by_name['response']
DESCRIPTOR.message_types_by_name['get_gossip_status_request'] = _GET_GOSSIP_STATUS_REQUEST
DESCRIPTOR.message_types_by_name['get_gossip_status_response'] = _GET_GOSSIP_STATUS_RESPONSE
DESCRIPTOR.message_types_by_name['p2p_request'] = _P2P_REQUEST
DESCRIPTOR.message_types_by_name['p2p_response'] = _P2P_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

get_gossip_status_request = _reflection.GeneratedProtocolMessageType('get_gossip_status_request', (_message.Message,), {
  'DESCRIPTOR' : _GET_GOSSIP_STATUS_REQUEST,
  '__module__' : 'koinos.rpc.p2p.p2p_rpc_pb2'
  # @@protoc_insertion_point(class_scope:koinos.rpc.p2p.get_gossip_status_request)
  })
_sym_db.RegisterMessage(get_gossip_status_request)

get_gossip_status_response = _reflection.GeneratedProtocolMessageType('get_gossip_status_response', (_message.Message,), {
  'DESCRIPTOR' : _GET_GOSSIP_STATUS_RESPONSE,
  '__module__' : 'koinos.rpc.p2p.p2p_rpc_pb2'
  # @@protoc_insertion_point(class_scope:koinos.rpc.p2p.get_gossip_status_response)
  })
_sym_db.RegisterMessage(get_gossip_status_response)

p2p_request = _reflection.GeneratedProtocolMessageType('p2p_request', (_message.Message,), {
  'DESCRIPTOR' : _P2P_REQUEST,
  '__module__' : 'koinos.rpc.p2p.p2p_rpc_pb2'
  # @@protoc_insertion_point(class_scope:koinos.rpc.p2p.p2p_request)
  })
_sym_db.RegisterMessage(p2p_request)

p2p_response = _reflection.GeneratedProtocolMessageType('p2p_response', (_message.Message,), {
  'DESCRIPTOR' : _P2P_RESPONSE,
  '__module__' : 'koinos.rpc.p2p.p2p_rpc_pb2'
  # @@protoc_insertion_point(class_scope:koinos.rpc.p2p.p2p_response)
  })
_sym_db.RegisterMessage(p2p_response)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
